### ISSUE TITLE
Process Watcher Failing on some users PC's

### ISSUE THREAD

**Issue by spdermn02** [spdermn02/TouchPortal_Discord_Plugin#30]
For some users the process watcher can't spawn the cmd in order to run the process watcher, need to try to determine why this is occurring as Command Prompt is installed on windows by default, and as far as I know can't be uninstalled.
```
15:29:41.688 - [ERROR] (Plugin Instance) events.js:292
15:29:41.689 - [ERROR] (Plugin Instance)       throw er; // Unhandled 'error' event
15:29:41.690 - [ERROR] (Plugin Instance)       ^
15:29:41.691 - [ERROR] (Plugin Instance) 
15:29:41.692 - [ERROR] (Plugin Instance) Error reading communication: Connection reset
15:29:41.692 - [ERROR] (Plugin Instance) Error: spawn cmd ENOENT
15:29:41.693 - [ERROR] (Plugin Instance) Plugin Connection has been incorrectly closed... 
15:29:41.693 - [ERROR] (Plugin Instance)     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
15:29:41.694 - [ERROR] (Plugin Instance) Connection has been closed... 
15:29:41.694 - [ERROR] (Plugin Instance)     at onErrorNT (internal/child_process.js:469:16)
15:29:41.695 - [ERROR] (Plugin Instance)     at processTicksAndRejections (internal/process/task_queues.js:84:21)
15:29:41.696 - [ERROR] (Plugin Instance) Emitted 'error' event on ChildProcess instance at:
15:29:41.697 - [ERROR] (Plugin Instance)     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
15:29:41.698 - [ERROR] (Plugin Instance)     at onErrorNT (internal/child_process.js:469:16)
15:29:41.699 - [ERROR] (Plugin Instance)     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
15:29:41.699 - [ERROR] (Plugin Instance)   errno: 'ENOENT',
15:29:41.700 - [ERROR] (Plugin Instance)   code: 'ENOENT',
15:29:41.701 - [ERROR] (Plugin Instance)   syscall: 'spawn cmd',
15:29:41.701 - [ERROR] (Plugin Instance)   path: 'cmd',
15:29:41.702 - [ERROR] (Plugin Instance)   spawnargs: [
15:29:41.703 - [ERROR] (Plugin Instance)     '/c',
15:29:41.704 - [ERROR] (Plugin Instance)     'WMIC path win32_process get Name,Processid,ParentProcessId,Commandline,ExecutablePath'
15:29:41.704 - [ERROR] (Plugin Instance)   ]
15:29:41.705 - [ERROR] (Plugin Instance) }
```

**Comment by spdermn02** [comment]
There is  a branch with a fix on it - Testing it locally I removed all C:\WINDOWS\System32 values from my Path in my system environment variables, and then ran my code (without the fix) and it got the same error, put the fix in place, and the process watcher worked as expected.
